// Currency metadata used for the searchable dropdown and the output table.
// `code` matches the keys in data/rates.json (lower-case ISO 4217).
// `label` is an optional display override (e.g. CNY shown as "RMB").
// `aliases` are extra search terms (country/region, common names).
//
// PRIORITY currencies are pinned to the top of the dropdown and are the
// fixed rows of the output table.

window.PRIORITY_CODES = ["sgd", "myr", "usd", "twd", "cny", "hkd"];

window.CURRENCIES = [
  // ----- high precedence -----
  { code: "sgd", name: "Singapore Dollar", country: "Singapore", flag: "🇸🇬" },
  { code: "myr", name: "Malaysian Ringgit", country: "Malaysia", flag: "🇲🇾" },
  { code: "usd", name: "US Dollar", country: "United States", flag: "🇺🇸" },
  { code: "twd", name: "New Taiwan Dollar", country: "Taiwan", flag: "🇹🇼" },
  { code: "cny", label: "RMB", name: "Chinese Yuan (Renminbi)", country: "China", flag: "🇨🇳", aliases: ["rmb", "renminbi", "yuan", "cny"] },
  { code: "hkd", name: "Hong Kong Dollar", country: "Hong Kong", flag: "🇭🇰" },

  // ----- rest (alphabetical-ish by country) -----
  { code: "aed", name: "UAE Dirham", country: "United Arab Emirates", flag: "🇦🇪", aliases: ["dubai", "abu dhabi"] },
  { code: "afn", name: "Afghan Afghani", country: "Afghanistan", flag: "🇦🇫" },
  { code: "all", name: "Albanian Lek", country: "Albania", flag: "🇦🇱" },
  { code: "amd", name: "Armenian Dram", country: "Armenia", flag: "🇦🇲" },
  { code: "ang", name: "Netherlands Antillean Guilder", country: "Curaçao / Sint Maarten", flag: "🇨🇼" },
  { code: "aoa", name: "Angolan Kwanza", country: "Angola", flag: "🇦🇴" },
  { code: "ars", name: "Argentine Peso", country: "Argentina", flag: "🇦🇷" },
  { code: "aud", name: "Australian Dollar", country: "Australia", flag: "🇦🇺" },
  { code: "awg", name: "Aruban Florin", country: "Aruba", flag: "🇦🇼" },
  { code: "azn", name: "Azerbaijani Manat", country: "Azerbaijan", flag: "🇦🇿" },
  { code: "bam", name: "Bosnia-Herzegovina Convertible Mark", country: "Bosnia and Herzegovina", flag: "🇧🇦" },
  { code: "bbd", name: "Barbadian Dollar", country: "Barbados", flag: "🇧🇧" },
  { code: "bdt", name: "Bangladeshi Taka", country: "Bangladesh", flag: "🇧🇩" },
  { code: "bgn", name: "Bulgarian Lev", country: "Bulgaria", flag: "🇧🇬" },
  { code: "bhd", name: "Bahraini Dinar", country: "Bahrain", flag: "🇧🇭" },
  { code: "bif", name: "Burundian Franc", country: "Burundi", flag: "🇧🇮" },
  { code: "bmd", name: "Bermudian Dollar", country: "Bermuda", flag: "🇧🇲" },
  { code: "bnd", name: "Brunei Dollar", country: "Brunei", flag: "🇧🇳" },
  { code: "bob", name: "Bolivian Boliviano", country: "Bolivia", flag: "🇧🇴" },
  { code: "brl", name: "Brazilian Real", country: "Brazil", flag: "🇧🇷" },
  { code: "bsd", name: "Bahamian Dollar", country: "Bahamas", flag: "🇧🇸" },
  { code: "btn", name: "Bhutanese Ngultrum", country: "Bhutan", flag: "🇧🇹" },
  { code: "bwp", name: "Botswanan Pula", country: "Botswana", flag: "🇧🇼" },
  { code: "byn", name: "Belarusian Ruble", country: "Belarus", flag: "🇧🇾" },
  { code: "bzd", name: "Belize Dollar", country: "Belize", flag: "🇧🇿" },
  { code: "cad", name: "Canadian Dollar", country: "Canada", flag: "🇨🇦" },
  { code: "cdf", name: "Congolese Franc", country: "DR Congo", flag: "🇨🇩" },
  { code: "chf", name: "Swiss Franc", country: "Switzerland", flag: "🇨🇭" },
  { code: "clp", name: "Chilean Peso", country: "Chile", flag: "🇨🇱" },
  { code: "cop", name: "Colombian Peso", country: "Colombia", flag: "🇨🇴" },
  { code: "crc", name: "Costa Rican Colón", country: "Costa Rica", flag: "🇨🇷" },
  { code: "cup", name: "Cuban Peso", country: "Cuba", flag: "🇨🇺" },
  { code: "cve", name: "Cape Verdean Escudo", country: "Cape Verde", flag: "🇨🇻" },
  { code: "czk", name: "Czech Koruna", country: "Czechia", flag: "🇨🇿" },
  { code: "djf", name: "Djiboutian Franc", country: "Djibouti", flag: "🇩🇯" },
  { code: "dkk", name: "Danish Krone", country: "Denmark", flag: "🇩🇰" },
  { code: "dop", name: "Dominican Peso", country: "Dominican Republic", flag: "🇩🇴" },
  { code: "dzd", name: "Algerian Dinar", country: "Algeria", flag: "🇩🇿" },
  { code: "egp", name: "Egyptian Pound", country: "Egypt", flag: "🇪🇬" },
  { code: "ern", name: "Eritrean Nakfa", country: "Eritrea", flag: "🇪🇷" },
  { code: "etb", name: "Ethiopian Birr", country: "Ethiopia", flag: "🇪🇹" },
  { code: "eur", name: "Euro", country: "Eurozone", flag: "🇪🇺", aliases: ["europe", "european union"] },
  { code: "fjd", name: "Fijian Dollar", country: "Fiji", flag: "🇫🇯" },
  { code: "fkp", name: "Falkland Islands Pound", country: "Falkland Islands", flag: "🇫🇰" },
  { code: "gbp", name: "British Pound Sterling", country: "United Kingdom", flag: "🇬🇧", aliases: ["uk", "britain", "england", "sterling", "pound"] },
  { code: "gel", name: "Georgian Lari", country: "Georgia", flag: "🇬🇪" },
  { code: "ghs", name: "Ghanaian Cedi", country: "Ghana", flag: "🇬🇭" },
  { code: "gip", name: "Gibraltar Pound", country: "Gibraltar", flag: "🇬🇮" },
  { code: "gmd", name: "Gambian Dalasi", country: "Gambia", flag: "🇬🇲" },
  { code: "gnf", name: "Guinean Franc", country: "Guinea", flag: "🇬🇳" },
  { code: "gtq", name: "Guatemalan Quetzal", country: "Guatemala", flag: "🇬🇹" },
  { code: "gyd", name: "Guyanaese Dollar", country: "Guyana", flag: "🇬🇾" },
  { code: "hnl", name: "Honduran Lempira", country: "Honduras", flag: "🇭🇳" },
  { code: "hrk", name: "Croatian Kuna", country: "Croatia", flag: "🇭🇷" },
  { code: "htg", name: "Haitian Gourde", country: "Haiti", flag: "🇭🇹" },
  { code: "huf", name: "Hungarian Forint", country: "Hungary", flag: "🇭🇺" },
  { code: "idr", name: "Indonesian Rupiah", country: "Indonesia", flag: "🇮🇩" },
  { code: "ils", name: "Israeli New Shekel", country: "Israel", flag: "🇮🇱" },
  { code: "inr", name: "Indian Rupee", country: "India", flag: "🇮🇳" },
  { code: "iqd", name: "Iraqi Dinar", country: "Iraq", flag: "🇮🇶" },
  { code: "irr", name: "Iranian Rial", country: "Iran", flag: "🇮🇷" },
  { code: "isk", name: "Icelandic Króna", country: "Iceland", flag: "🇮🇸" },
  { code: "jmd", name: "Jamaican Dollar", country: "Jamaica", flag: "🇯🇲" },
  { code: "jod", name: "Jordanian Dinar", country: "Jordan", flag: "🇯🇴" },
  { code: "jpy", name: "Japanese Yen", country: "Japan", flag: "🇯🇵" },
  { code: "kes", name: "Kenyan Shilling", country: "Kenya", flag: "🇰🇪" },
  { code: "kgs", name: "Kyrgystani Som", country: "Kyrgyzstan", flag: "🇰🇬" },
  { code: "khr", name: "Cambodian Riel", country: "Cambodia", flag: "🇰🇭" },
  { code: "kmf", name: "Comorian Franc", country: "Comoros", flag: "🇰🇲" },
  { code: "kpw", name: "North Korean Won", country: "North Korea", flag: "🇰🇵" },
  { code: "krw", name: "South Korean Won", country: "South Korea", flag: "🇰🇷", aliases: ["korea"] },
  { code: "kwd", name: "Kuwaiti Dinar", country: "Kuwait", flag: "🇰🇼" },
  { code: "kyd", name: "Cayman Islands Dollar", country: "Cayman Islands", flag: "🇰🇾" },
  { code: "kzt", name: "Kazakhstani Tenge", country: "Kazakhstan", flag: "🇰🇿" },
  { code: "lak", name: "Laotian Kip", country: "Laos", flag: "🇱🇦" },
  { code: "lbp", name: "Lebanese Pound", country: "Lebanon", flag: "🇱🇧" },
  { code: "lkr", name: "Sri Lankan Rupee", country: "Sri Lanka", flag: "🇱🇰" },
  { code: "lrd", name: "Liberian Dollar", country: "Liberia", flag: "🇱🇷" },
  { code: "lsl", name: "Lesotho Loti", country: "Lesotho", flag: "🇱🇸" },
  { code: "lyd", name: "Libyan Dinar", country: "Libya", flag: "🇱🇾" },
  { code: "mad", name: "Moroccan Dirham", country: "Morocco", flag: "🇲🇦" },
  { code: "mdl", name: "Moldovan Leu", country: "Moldova", flag: "🇲🇩" },
  { code: "mga", name: "Malagasy Ariary", country: "Madagascar", flag: "🇲🇬" },
  { code: "mkd", name: "Macedonian Denar", country: "North Macedonia", flag: "🇲🇰" },
  { code: "mmk", name: "Myanmar Kyat", country: "Myanmar", flag: "🇲🇲", aliases: ["burma"] },
  { code: "mnt", name: "Mongolian Tugrik", country: "Mongolia", flag: "🇲🇳" },
  { code: "mop", name: "Macanese Pataca", country: "Macau", flag: "🇲🇴" },
  { code: "mru", name: "Mauritanian Ouguiya", country: "Mauritania", flag: "🇲🇷" },
  { code: "mur", name: "Mauritian Rupee", country: "Mauritius", flag: "🇲🇺" },
  { code: "mvr", name: "Maldivian Rufiyaa", country: "Maldives", flag: "🇲🇻" },
  { code: "mwk", name: "Malawian Kwacha", country: "Malawi", flag: "🇲🇼" },
  { code: "mxn", name: "Mexican Peso", country: "Mexico", flag: "🇲🇽" },
  { code: "mzn", name: "Mozambican Metical", country: "Mozambique", flag: "🇲🇿" },
  { code: "nad", name: "Namibian Dollar", country: "Namibia", flag: "🇳🇦" },
  { code: "ngn", name: "Nigerian Naira", country: "Nigeria", flag: "🇳🇬" },
  { code: "nio", name: "Nicaraguan Córdoba", country: "Nicaragua", flag: "🇳🇮" },
  { code: "nok", name: "Norwegian Krone", country: "Norway", flag: "🇳🇴" },
  { code: "npr", name: "Nepalese Rupee", country: "Nepal", flag: "🇳🇵" },
  { code: "nzd", name: "New Zealand Dollar", country: "New Zealand", flag: "🇳🇿" },
  { code: "omr", name: "Omani Rial", country: "Oman", flag: "🇴🇲" },
  { code: "pab", name: "Panamanian Balboa", country: "Panama", flag: "🇵🇦" },
  { code: "pen", name: "Peruvian Sol", country: "Peru", flag: "🇵🇪" },
  { code: "pgk", name: "Papua New Guinean Kina", country: "Papua New Guinea", flag: "🇵🇬" },
  { code: "php", name: "Philippine Peso", country: "Philippines", flag: "🇵🇭" },
  { code: "pkr", name: "Pakistani Rupee", country: "Pakistan", flag: "🇵🇰" },
  { code: "pln", name: "Polish Złoty", country: "Poland", flag: "🇵🇱" },
  { code: "pyg", name: "Paraguayan Guarani", country: "Paraguay", flag: "🇵🇾" },
  { code: "qar", name: "Qatari Rial", country: "Qatar", flag: "🇶🇦" },
  { code: "ron", name: "Romanian Leu", country: "Romania", flag: "🇷🇴" },
  { code: "rsd", name: "Serbian Dinar", country: "Serbia", flag: "🇷🇸" },
  { code: "rub", name: "Russian Ruble", country: "Russia", flag: "🇷🇺" },
  { code: "rwf", name: "Rwandan Franc", country: "Rwanda", flag: "🇷🇼" },
  { code: "sar", name: "Saudi Riyal", country: "Saudi Arabia", flag: "🇸🇦" },
  { code: "sbd", name: "Solomon Islands Dollar", country: "Solomon Islands", flag: "🇸🇧" },
  { code: "scr", name: "Seychellois Rupee", country: "Seychelles", flag: "🇸🇨" },
  { code: "sdg", name: "Sudanese Pound", country: "Sudan", flag: "🇸🇩" },
  { code: "sek", name: "Swedish Krona", country: "Sweden", flag: "🇸🇪" },
  { code: "shp", name: "Saint Helena Pound", country: "Saint Helena", flag: "🇸🇭" },
  { code: "sll", name: "Sierra Leonean Leone", country: "Sierra Leone", flag: "🇸🇱" },
  { code: "sos", name: "Somali Shilling", country: "Somalia", flag: "🇸🇴" },
  { code: "srd", name: "Surinamese Dollar", country: "Suriname", flag: "🇸🇷" },
  { code: "ssp", name: "South Sudanese Pound", country: "South Sudan", flag: "🇸🇸" },
  { code: "stn", name: "São Tomé and Príncipe Dobra", country: "São Tomé and Príncipe", flag: "🇸🇹" },
  { code: "svc", name: "Salvadoran Colón", country: "El Salvador", flag: "🇸🇻" },
  { code: "syp", name: "Syrian Pound", country: "Syria", flag: "🇸🇾" },
  { code: "szl", name: "Swazi Lilangeni", country: "Eswatini", flag: "🇸🇿" },
  { code: "thb", name: "Thai Baht", country: "Thailand", flag: "🇹🇭" },
  { code: "tjs", name: "Tajikistani Somoni", country: "Tajikistan", flag: "🇹🇯" },
  { code: "tmt", name: "Turkmenistani Manat", country: "Turkmenistan", flag: "🇹🇲" },
  { code: "tnd", name: "Tunisian Dinar", country: "Tunisia", flag: "🇹🇳" },
  { code: "top", name: "Tongan Paʻanga", country: "Tonga", flag: "🇹🇴" },
  { code: "try", name: "Turkish Lira", country: "Turkey", flag: "🇹🇷", aliases: ["turkiye"] },
  { code: "ttd", name: "Trinidad and Tobago Dollar", country: "Trinidad and Tobago", flag: "🇹🇹" },
  { code: "tzs", name: "Tanzanian Shilling", country: "Tanzania", flag: "🇹🇿" },
  { code: "uah", name: "Ukrainian Hryvnia", country: "Ukraine", flag: "🇺🇦" },
  { code: "ugx", name: "Ugandan Shilling", country: "Uganda", flag: "🇺🇬" },
  { code: "uyu", name: "Uruguayan Peso", country: "Uruguay", flag: "🇺🇾" },
  { code: "uzs", name: "Uzbekistani Som", country: "Uzbekistan", flag: "🇺🇿" },
  { code: "ves", name: "Venezuelan Bolívar", country: "Venezuela", flag: "🇻🇪" },
  { code: "vnd", name: "Vietnamese Dong", country: "Vietnam", flag: "🇻🇳" },
  { code: "vuv", name: "Vanuatu Vatu", country: "Vanuatu", flag: "🇻🇺" },
  { code: "wst", name: "Samoan Tala", country: "Samoa", flag: "🇼🇸" },
  { code: "xaf", name: "Central African CFA Franc", country: "Central Africa (CEMAC)", flag: "🌍" },
  { code: "xcd", name: "East Caribbean Dollar", country: "Eastern Caribbean", flag: "🌎" },
  { code: "xof", name: "West African CFA Franc", country: "West Africa (UEMOA)", flag: "🌍" },
  { code: "xpf", name: "CFP Franc", country: "French Pacific", flag: "🇵🇫" },
  { code: "yer", name: "Yemeni Rial", country: "Yemen", flag: "🇾🇪" },
  { code: "zar", name: "South African Rand", country: "South Africa", flag: "🇿🇦" },
  { code: "zmw", name: "Zambian Kwacha", country: "Zambia", flag: "🇿🇲" },
  { code: "zwl", name: "Zimbabwean Dollar", country: "Zimbabwe", flag: "🇿🇼" },
];
